export const Colors = {
  primary: '#E8622A',
  primaryLight: '#FDEEE7',
  primaryDark: '#C04E1C',
  background: '#FAFAF8',
  surface: '#FFFFFF',
  border: '#EBEBEB',
  textPrimary: '#1A1A1A',
  textSecondary: '#6B6B6B',
  textMuted: '#A0A0A0',
  success: '#3DAB6E',
  halalGreen: '#D4EDDA',
  halalGreenText: '#1D6B35',
  spicyRed: '#FDEAEA',
  spicyRedText: '#C0392B',
  veggieGreen: '#E8F5E9',
  veggieGreenText: '#2E7D32',
};